name: tranding-engine


# =============================================================================
# Сети — изолируем трафик
# =============================================================================
networks:
  backend:
  # backend — для общения сервисов между собой (БД, Kafka)
  # приложение не должно напрямую смотреть в интернет
    driver: bridge
    internal: false # разрешаем исходящий трафик для скачивания данных


# =============================================================================
# Volumes — персистентные данные
# =============================================================================
volumes:
  postgres_data:
  kafka_data:
  zookeeper_data:

# =============================================================================
# Сервисы
# =============================================================================
